version: '3.4'
services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    expose:
      - 5434    
    container_name: minimalAppDb
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets