version: '3.4'
services:
  minimal-api:
    # Build image from the Dockerfile located in the current dir
    build: .
    image: minimal-api
    restart: always
    ports:
    - 8000:80
    environment:
      ASPNETCORE_URLS: http://+:80

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    environment:
      - MSSQL_SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    expose:
      - 5434    
    container_name: minimalAppDb
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets