version: '3.4'
services:
  example-web-api:
    # Build image from the Dockerfile located in the current dir
    build: .
    image: minimal-api
    restart: always
    ports:
    - 8000:80
    environment:
      ASPNETCORE_URLS: http://+:80
